import type { Metadata } from "next";
import { Cormorant_Garamond, Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/layout/Navigation";
import Footer from "@/components/layout/Footer";
import JsonLd from "@/components/seo/JsonLd";
import SmoothScroll from "@/components/shared/SmoothScroll";

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  style: ["normal", "italic"],
  variable: "--font-cormorant",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    default: "AI Intelligent Services | Premium Smart Home & Corporate AV",
    template: "%s | AI Intelligent Services",
  },
  description:
    "Award-winning smart home automation and corporate AV integration. Crestron, RTI, Q-SYS specialists serving discerning clients across the country. 15+ years of world-class programming expertise.",
  keywords: [
    "smart home automation",
    "Crestron programming",
    "RTI integration",
    "Q-SYS",
    "corporate AV",
    "home theater",
    "luxury home automation",
    "AV integrator",
    "AI smart home",
    "Lutron",
  ],
  authors: [{ name: "AI Intelligent Services" }],
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://intelligentai.systems",
    siteName: "AI Intelligent Services",
    title: "AI Intelligent Services | Premium Smart Home & Corporate AV",
    description:
      "Where technology meets architecture. Premium smart home automation and corporate AV integration powered by Crestron, RTI, and Q-SYS expertise.",
    // Open Graph image is generated by src/app/opengraph-image.tsx (branded card).
  },
  twitter: {
    card: "summary_large_image",
    title: "AI Intelligent Services | Premium Smart Home & Corporate AV",
    description:
      "Where technology meets architecture. Premium smart home automation and corporate AV integration.",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: "/favicon.ico",
  },
  metadataBase: new URL("https://intelligentai.systems"),
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${cormorant.variable} ${inter.variable}`}
      suppressHydrationWarning
    >
      <body className="antialiased">
        <SmoothScroll />
        <JsonLd />
        <a href="#main" className="skip-link">
          Skip to content
        </a>
        <Navigation />
        <main id="main">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
